language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25

jdk:
- oraclejdk8

before_install:
- nvm install 6

install:
- npm install -g cordova gulp ionic
- npm install
- gulp install

script:
- ionic resources android
- ionic platform add android
- ionic build android
