matrix:
  include:
  - language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - extra
      - build-tools-28.0.3
      - android-28
    script:
    - cordova platform add android
    - cordova build android -- --packageType=bundle
  - language: python
    python: 2.7
    install: pip install tox
    script: tox -e flake8,py27
  - language: python
    python: 3.7
    install: pip install tox
    script: tox -e flake8,py37
  - language: python
    python: 3.8
    install: pip install tox
    script: tox -e flake8,py38

before_install:
- nvm install 8

install:
- npm install -g cordova gulp
- npm install
- gulp install
- gulp dist
