language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra
    - build-tools-28.0.3
    - android-28

before_install:
- nvm install 8

install:
- npm install -g cordova gulp
- npm install
- gulp install

script:
- gulp dist
- cordova platform add android
- cordova build android -- --packageType=bundle
